# Generated by Django 3.0.6 on 2020-06-12 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200609_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='total',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 5, 37, 18, 806985, tzinfo=utc)),
        ),
    ]
